### PR TITLE
Add annotations text labels

### PR DESCRIPTION
**Pull request by siennawishart**
image
image

### CODE REVIEW

**Review by MickeyDang — COMMENTED** [review]
Makes sense to me :) . Can we add a box around the input and button so that it has a bit of padding to seem like one thing - matching the figma design.

Otherwise, happy to give the thumbs up.

**Comment by MickeyDang** [comment]
Also, how hard is it to add this translucent background for the text matching the figma? If too hard should be ok, just double check w Queenie.

Screen Shot 2022-03-06 at 6 43 45 PM

**Comment by siennawishart** [comment]
> Makes sense to me :) . Can we add a box around the input and button so that it has a bit of padding to seem like one thing - matching the figma design.
> 
> Otherwise, happy to give the thumbs up.

image
 How's this? I used the same CSS as the annotation bar

**Comment by MickeyDang** [comment]
Yep, push changes and I'll thumbs up :)

**Comment by siennawishart** [comment]
> Also, how hard is it to add this translucent background for the text matching the figma? If too hard should be ok, just double check w Queenie.
> 
> Screen Shot 2022-03-06 at 6 43 45 PM



> Also, how hard is it to add this translucent background for the text matching the figma? If too hard should be ok, just double check w Queenie.
> 
> Screen Shot 2022-03-06 at 6 43 45 PM

There isn't a straightforward way, I just messaged queenie to check, she also said the text looked fine earlier

**Review by MickeyDang — APPROVED** [review]
LGTM ✅  🎈 🚢  !

**Pull request merged**
